services:
  srv:
    container_name: wg-server
    build: .
    command: "bash /data/init.sh"
    volumes:
      - ./scripts:/data
      - ./config:/wgconf
      - ./serverdata:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.forwarding=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.eth0.proxy_ndp=1
    ports:
      - 12001:12001/udp
    networks:
      - internal

networks:
  internal:
    enable_ipv6: true
    driver: bridge